In [1]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
items=['TV','냉장고','전자렌지','컴퓨터', '선풍기','선풍기', '믹서','믹서' ]

encoder=LabelEncoder()
encoder.fit(items)
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자렌지', '컴퓨터'], dtype='<U4')

In [2]:
labels = encoder.transform(items)
print(labels)

[0 1 4 5 3 3 2 2]


In [3]:
encoder.inverse_transform([0,1,2,3,4,5])

array(['TV', '냉장고', '믹서', '선풍기', '전자렌지', '컴퓨터'], dtype='<U4')

In [20]:
labels = labels.reshape(-1,1)
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
print(f'type(oh_encoder) : {type(oh_encoder)}') # oh_encoder.shape : error (object has no arrtibute)

type(oh_encoder) : <class 'sklearn.preprocessing._encoders.OneHotEncoder'>


/opt/conda/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [21]:
oh_labels = oh_encoder.transform(labels)
print(f'type(oh_labels) : {type(oh_labels)}, oh_labels.shape : {oh_labels.shape}')
print(f'oh_labels.toarray() : \n{oh_labels.toarray()}')

type(oh_labels) : <class 'scipy.sparse.csr.csr_matrix'>, oh_labels.shape : (8, 6)
oh_labels.toarray() : 
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [6]:
import pandas as pd
df = pd.DataFrame({'items':['TV','냉장고','전자렌지','컴퓨터', '선풍기','선풍기', '믹서','믹서' ]})
df

items
0    TV
1   냉장고
2  전자렌지
3   컴퓨터
4   선풍기
5   선풍기
6    믹서
7    믹서

In [7]:
pd.get_dummies(df)

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자렌지  items_컴퓨터
0         1          0         0          0           0          0
1         0          1         0          0           0          0
2         0          0         0          0           1          0
3         0          0         0          0           0          1
4         0          0         0          1           0          0
5         0          0         0          1           0          0
6         0          0         1          0           0          0
7         0          0         1          0           0          0

In [8]:
#ndarray 변환
pd.get_dummies(df).values

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0]], dtype=uint8)

In [9]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(iris_data, columns=iris.feature_names)
print(f'iris_df.mean():\n{iris_df.mean()}')
print(f'iris_df.var():\n{iris_df.var()}')

iris_df.mean():
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
iris_df.var():
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() # 평균 0, 분산1인 정규분포
scaler.fit(iris_data) # iris_df 입력이나 iris_data(nd.array) 같다
iris_scaled = scaler.transform(iris_data) # df -> ndarray 변환
print(f'type(iris_scaled) : {type(iris_scaled)}')
print(f'iris_scaled.mean() : {iris_scaled.mean()}')
print(f'iris_scaled.var() : {iris_scaled.var()}\n')

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print(f'type(iris_df_scaled) :\n{type(iris_df_scaled)}\n')
print(f'iris_df_scaled.mean() :\n{iris_df_scaled.mean()}\n')
print(f'iris_df_scaled.var() :\n{iris_df_scaled.var()}\n')

type(iris_scaled) : <class 'numpy.ndarray'>
iris_scaled.mean() : -1.4684549872375404e-15
iris_scaled.var() : 1.0

type(iris_df_scaled) :
<class 'pandas.core.frame.DataFrame'>

iris_df_scaled.mean() :
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

iris_df_scaled.var() :
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64



In [11]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

scaler.fit(iris_data) #iris_df iris_data 상관없음
iris_scaled = scaler.transform(iris_data) # df일경우 nd로 전환됨

#nd에는 집합함수 없어?하여 df이용
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print(f'type(iris_df_scaled) : {type(iris_df_scaled)}\n')
print(f'iris_df_scaled.min() :\n{iris_df_scaled.min()}\n')
print(f'iris_df_scaled.max() :\n{iris_df_scaled.max()}\n')


type(iris_df_scaled) : <class 'pandas.core.frame.DataFrame'>

iris_df_scaled.min() :
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

iris_df_scaled.max() :
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64

